version: "3.4"
x-logging:
  &logging
  logging:
    options:
      max-size: 10m
      max-file: "3"
services:
  taiko_pool_client:
    container_name: taiko_pool_client
    image: ghcr.io/davaymne/taiko-pool-proverd-alpha5:main
    restart: unless-stopped
    command:
      - --proverPort
      - "${PROVER_PORT}"
      - --proverWallet
      - "${PROVER_WALLET}"
      - --proverName
      - "${PROVER_NAME}"
    <<: *logging
  zkevm_chain_prover_rpcd_client:
    container_name: zkevm_chain_prover_rpcd_client
    image: gcr.io/evmchain/jolnir-proverd:latest
    restart: unless-stopped
    ports:
      - "${PROVER_PORT}:9000"
    pull_policy: always 
    env_file:
      - .env
    volumes:
      - ./scripts:/script
      - zkevm_chain_prover_rpcd_data:/data
    entrypoint:
      - /bin/sh
      - -c
      - "/script/start-zkevm-chain-rpcd.sh"
    deploy:
      replicas: ${ZKEVM_CHAIN_INSTANCES_NUM:-1}
      resources:
        limits:
          memory: 32G
    <<: *logging
volumes:
  zkevm_chain_prover_rpcd_data:
